version: '2' # specify docker-compose version

services:
  web:
    build:
      context: ../rr-web-app
      dockerfile: ../rr-web-app/docker/Dockerfile
    ports:
      - "80:80"
    stdin_open: true
    tty: true
    depends_on:
      - api

  api:
    build:
      context: ../rr-api
      dockerfile: ../rr-api/docker/Dockerfile
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=root"